### ISSUE TITLE
Make recipient(s) optional

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-contactform#27]
When you process the submitted form data in a callback function, there are cases where you don't want to have the contact form's details to be sent to recipients. Therefore it should be possible to not set the recipients property or to assign an empty array.

**Comment by nadar** [comment]
I just did some research on the contact form controller. If we allow empty recipients the whole controller makes no sense anymore, even the callbacks rely on the fact that the contactform (name of the module) is sent. 

So maybe we should adjust the use case you have in the project, instead of the changing the mechanism of contactform, which actually has the core function of "sending an email after fill in the contact form".
